client/src/MobicoopBundle/JsonLD/Entity/Hydra.php
<?php

/**
 * Copyright (c) 2018, MOBICOOP. All rights reserved.
 * This project is dual licensed under AGPL and proprietary licence.
 ***************************
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <gnu.org/licenses>.
 ***************************
 *    Licence MOBICOOP described in the file
 *    LICENSE
 **************************/

namespace Mobicoop\Bundle\MobicoopBundle\JsonLD\Entity;

/**
 * A hydra collection object (returned by a JSON-LD Rest API).
 */
class Hydra
{
    
    /**
     * @var string $context The context of the collection.
     */
    private $context;
    
    /**
     * @var int $id The id of the collection.
     */
    private $id;
    
    /**
     * @var string $type The type of the collection.
     */
    private $type;
    
    /**
     * @var array $member The hydra member.
     */
    private $member;
    
    /**
     * @var int $totalItems The total number of items of the collection.
     */
    private $totalItems;
    
    /**
     * @var string $title
     *   Title of the hydra
     */
    private $title;
    
    /**
     * @var string $description
     *   Description of the hydra
     */
    private $description;
    /**
     * @var Trace[] $traces
     */
    private $traces;
    
    /**
     * @var HydraView $view The view of the collection.
     */
    private $view;
    
    /**
     * @param mixed $member
     */
    public function addMember($member)
    {
        $this->member[] = $member;
    }
    
    /**
     * @param int $key
     */
    public function removeMember(int $key)
    {
        array_splice($this->member, $key, 1);
    }
    
    /**
     * @param Trace $trace
     */
    public function addTrace(Trace $trace)
    {
        $this->traces[] = $trace;
    }
    
    /**
     * @param int $key
     */
    public function removeTrace(int $key)
    {
        array_splice($this->traces, $key, 1);
    }
    
    
    public function getId()
    {
        return $this->id;
    }

    public function getContext()
    {
        return $this->context;
    }

    public function getType()
    {
        return $this->type;
    }

    public function getMember()
    {
        return $this->member;
    }

    public function getTotalItems()
    {
        return $this->totalItems;
    }

    public function getView()
    {
        return $this->view;
    }

    public function setId($id)
    {
        $this->id = $id;
    }

    public function setContext($context)
    {
        $this->context = $context;
    }

    public function setType($type)
    {
        $this->type = $type;
    }

    public function setMember($member)
    {
        $this->member = $member;
    }
    
    public function setTotalItems($totalItems)
    {
        $this->totalItems = $totalItems;
    }

    public function setView($view)
    {
        $this->view = $view;
    }
    
    /**
     * Recupere le titre de l'hydra.
     *
     * @return string
     */
    public function getTitle(): ?string
    {
        return $this->title;
    }
    
    /**
     * Initialise le titre de l'hydra.
     *
     * @param string $title
     */
    public function setTitle(string $title)
    {
        $this->title = $title;
    }
    
    /**
     * Recupere la description de l'hydra.
     *
     * @return string
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }
    
    /**
     * Initialise la description de l'hydra.
     *
     * @param string $description
     */
    public function setDescription(string $description)
    {
        $this->description = $description;
    }
    
    /**
     * @return Trace[]
     */
    public function getTraces(): ?array
    {
        return $this->traces;
    }
    
    /**
     * @param Trace[] $traces
     */
    public function setTraces(array $traces)
    {
        $this->traces = $traces;
    }
}

client/src/MobicoopBundle/JsonLD/Entity/HydraView.php
<?php

/**
 * Copyright (c) 2018, MOBICOOP. All rights reserved.
 * This project is dual licensed under AGPL and proprietary licence.
 ***************************
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Affero General Public License as
 *    published by the Free Software Foundation, either version 3 of the
 *    License, or (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <gnu.org/licenses>.
 ***************************
 *    Licence MOBICOOP described in the file
 *    LICENSE
 **************************/

namespace Mobicoop\Bundle\MobicoopBundle\JsonLD\Entity;

/**
 * A hydra view from an hydra collection object.
 */
class HydraView implements \JsonSerializable
{
    
    /**
     * @var int $id The id of the view.
     */
    private $id;
    
    /**
     * @var string The type of the view.
     */
    private $type;
    
    /**
     * @var string The first item of the view.
     */
    private $first;

    /**
     * @var string The last item of the view.
     */
    private $last;
    
    /**
     * @var string The next item of the view.
     */
    private $next;
    
    /**
     * @var string The previous item of the view.
     */
    private $previous;

    public function getId()
    {
        return $this->id;
    }

    public function getType()
    {
        return $this->type;
    }

    public function getFirst()
    {
        return $this->first;
    }

    public function getLast()
    {
        return $this->last;
    }

    public function getNext()
    {
        return $this->next;
    }

    public function getPrevious()
    {
        return $this->previous;
    }

    public function setId($id)
    {
        $this->id = $id;
    }

    public function setType($type)
    {
        $this->type = $type;
    }

    public function setFirst($first)
    {
        $this->first = $first;
    }

    public function setLast($last)
    {
        $this->last = $last;
    }

    public function setNext($next)
    {
        $this->next = $next;
    }

    public function setPrevious($previous)
    {
        $this->$previous = $previous;
    }

    public function jsonSerialize()
    {
        return
        [
            'id'                => $this->getId(),
            'type'                => $this->getType(),
            'first'                => $this->getFirst(),
            'last'                => $this->getLast(),
            'next'                => $this->getNext(),
            'previous'                => $this->getPrevious(),
        ];
    }
}

client/src/MobicoopBundle/JsonLD/Entity/Trace.php
<?php
/**
 * Created by PhpStorm.
 * User= vagrant
 * Date= 8/13/19
 * Time= 12=41 PM
 */

namespace Mobicoop\Bundle\MobicoopBundle\JsonLD\Entity;

use http\Exception\InvalidArgumentException;
use Symfony\Bundle\FrameworkBundle\Translation\Translator;

class Trace
{
    /**
     * @var string $namespace;
     */
    private $namespace;
    /**
     * @var string $short_class
     */
    private $short_class= "";
    /**
     * @var string $class
     */
    private $class= "";
    /**
     * @var string $type
     */
    private $type= "";
    /**
     * @var string $function
     */
    private $function= "";
    /**
     * @var string $file
     */
    private $file= "";
    /**
     * @var int $line
     */
    private $line= 0;
    /**
     * @var array $args
     */
    private $args= [];
    
    /**
     * Trace constructor.
     */
    public function __construct()
    {
        $ctp = func_num_args();
        $args = func_get_args();
        if ($ctp!=1 && $ctp!=8) {
            throw new InvalidArgumentException('Bad parameters provided!');
        }
        list($namespace, $short_class, $class, $type, $function, $file, $line, $args) = array_values((($ctp==1)?reset($args): $args));
        $this->namespace = $namespace;
        $this->short_class = $short_class;
        $this->class = $class;
        $this->type = $type;
        $this->function = $function;
        $this->file = $file;
        $this->line = $line;
        $this->args = $args;
    }
    
    /**
     * @return string
     */
    public function getNamespace(): string
    {
        return $this->namespace;
    }
    
    /**
     * @param string $namespace
     */
    public function setNamespace(string $namespace): void
    {
        $this->namespace = $namespace;
    }
    
    /**
     * @return string
     */
    public function getShortClass(): string
    {
        return $this->short_class;
    }
    
    /**
     * @param string $short_class
     */
    public function setShortClass(string $short_class): void
    {
        $this->short_class = $short_class;
    }
    
    /**
     * @return string
     */
    public function getClass(): string
    {
        return $this->class;
    }
    
    /**
     * @param string $class
     */
    public function setClass(string $class): void
    {
        $this->class = $class;
    }
    
    /**
     * @return string
     */
    public function getType(): string
    {
        return $this->type;
    }
    
    /**
     * @param string $type
     */
    public function setType(string $type): void
    {
        $this->type = $type;
    }
    
    /**
     * @return string
     */
    public function getFunction(): string
    {
        return $this->function;
    }
    
    /**
     * @param string $function
     */
    public function setFunction(string $function): void
    {
        $this->function = $function;
    }
    
    /**
     * @return string
     */
    public function getFile(): string
    {
        return $this->file;
    }
    
    /**
     * @param string $file
     */
    public function setFile(string $file): void
    {
        $this->file = $file;
    }
    
    /**
     * @return int
     */
    public function getLine(): int
    {
        return $this->line;
    }
    
    /**
     * @param int $line
     */
    public function setLine(int $line): void
    {
        $this->line = $line;
    }
    
    /**
     * @return array
     */
    public function getArgs(): array
    {
        return $this->args;
    }
    
    /**
     * @param array $args
     */
    public function setArgs(array $args): void
    {
        $this->args = $args;
    }
    
    /**
     * Traces Loader.
     *
     * @param array $array
     * @return Trace[] array
     */
    public static function load(array $array): array
    {
        $traces= [];
        foreach ($array as $key=>$value) {
            $traces[]= new Trace((array)$value);
        }
        return $traces;
    }
}

client/src/MobicoopBundle/Resources/views/hydra/error.html.twig
{% extends '@Mobicoop/base.html.twig' %}
{# @var hydra \Mobicoop\Bundle\MobicoopBundle\JsonLD\Entity\Hydra #}
{% block title %}
    {{ "Une erreur est survenue!"|trans }}
{% endblock %}

{% block stylesheets %}
    {#{{ encore_entry_link_tags("#{assets_prefix ?? ''}home/home") }}#}
{% endblock %}

{% block main %}
    <div style="margin-left: 10px; margin-right: 10px; margin-bottom: 20px">
        <p><span>{{ "ID"|trans }}: </span><span>{{ hydra.id }}</span></p>
        <p><span>{{ "Contexte"|trans }}: </span><span>{{ hydra.context }}</span></p>
        <p><span>{{ "Type"|trans }}: </span><span>{{ hydra.type }}</span></p>
        <p><span>{{ "Titre"|trans }}: </span><span>{{ hydra.title }}</span></p>
        <p><span>{{ "Description"|trans }}: </span><span>{{ hydra.description }}</span></p>
        <br/>
        {% if app.debug %}
            <div>
                <h1>Traces</h1>
                <table border="1">
                    <thead>
                    <th><span>{{ "Namespace"|trans }}:</span></th>
                    <th><span>{{ "Nom de Classe"|trans }}:</span></th>
                    <th><span>{{ "Nom complet de la Classe"|trans }}:</span></th>
                    <th><span>{{ "Type"|trans }}: </span></th>
                    <th><span>{{ "Fonction"|trans }}:</span></th>
                    <th><span>{{ "Fichier"|trans }}: </span></th>
                    <th><span>{{ "ligne"|trans }}: </span></th>
                    <th><span>{{ "Arguments"|trans }}</span></th>
                    </thead>
                    <tbody>
                    {# @var trace \Mobicoop\Bundle\MobicoopBundle\JsonLD\Entity\Trace #}
                    {% for trace in hydra.traces %}
                        <tr>
                            <td><span>{{ trace.namespace }}</span></td>
                            <td><span>{{ trace.shortClass }}</span></td>
                            <td><span>{{ trace.class }}</span></td>
                            <td><span>{{ trace.type }}</span></td>
                            <td><span>{{ trace.function }}</span></td>
                            <td><span>{{ trace.file }}</span></td>
                            <td><span>{{ trace.line }}</span></td>
                            <td>
                                <ol>
                                    {% for arg in trace.args %}
                                        <li>
                                            <ul>
                                                <li><span>{{ "Type"|trans }}: </span><span>{{ arg[0] }}</span></li>
                                                {#todo : updgrade to handle array in arg[1]#}
                                                <li><span>{{ "Valeur"|trans }}: </span><span>{% if arg[1] is not iterable %} {{ arg[1] }} {% endif %}</span></li>
                                            </ul>
                                        </li>
                                    {% endfor %}
                                </ol>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                    <tfoot></tfoot>
                </table>
            </div>
        {% else %}
            Veuillez contacter l'administrateur!!!
        {% endif %}
    </div>
{% endblock %}